### ISSUE TITLE
Can't use the bot.

### ISSUE THREAD

**Issue by kaxonomy** [Moudoux/DiscordSelfBot#3]
I tried to use the bot, but it didn't work at all. Here is the log:
```12:51:31.260 [main] INFO  me.alexander.discordbot.Main - Starting SelfBot version 0.4
12:51:32.261 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Checking token **************************************************Xj8aAakBE
12:51:32.888 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Checked token **************************************************Xj8aAakBE (valid: true)
12:51:32.888 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Requesting gateway (token: **************************************************Xj8aAakBE)
12:51:32.920 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Requested gateway wss://gateway.discord.gg (token: **************************************************Xj8aAakBE)
12:51:33.273 [ReadingThread] DEBUG d.b.j.utils.DiscordWebsocketAdapter - Sending identify packet
12:51:33.273 [ReadingThread] DEBUG d.b.j.utils.DiscordWebsocketAdapter - Received HELLO packet
12:51:33.888 [ReadingThread] WARN  d.b.javacord.utils.PacketHandler - Couldn't handle packet of type READY. Please contact the developer! (packet: <insert super long error here>
org.json.JSONException: JSONObject["type"] not a string.
        at org.json.JSONObject.getString(JSONObject.java:658) ~[SelfBot.jar:na]
        at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:111) ~[SelfBot.jar:na]
        at de.btobastian.javacord.utils.handler.ReadyHandler.handle(ReadyHandler.java:53) ~[SelfBot.jar:na]
        at de.btobastian.javacord.utils.PacketHandler.handlePacket(PacketHandler.java:80) ~[SelfBot.jar:na]
        at de.btobastian.javacord.utils.DiscordWebsocketAdapter.onTextMessage(DiscordWebsocketAdapter.java:155) [SelfBot.jar:na]
        at de.btobastian.javacord.utils.DiscordWebsocketAdapter.onBinaryMessage(DiscordWebsocketAdapter.java:246) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:272) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:992) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:751) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110) [SelfBot.jar:na]
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66) [SelfBot.jar:na]
12:59:34.353 [ReadingThread] DEBUG d.b.j.utils.DiscordWebsocketAdapter - Received READY packet
12:59:34.356 [Timer-0] DEBUG d.b.j.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)
12:59:36.546 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Trying request/find user with id 225793393974837249 who isn't cached
12:59:36.636 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - No user with id 225793393974837249 was found
12:59:51.061 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Trying request/find user with id 268465843053133824 who isn't cached
12:59:51.213 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - No user with id 268465843053133824 was found
13:00:09.106 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - Trying request/find user with id 327619532292096000 who isn't cached
13:00:09.198 [pool-2-thread-1] DEBUG d.btobastian.javacord.ImplDiscordAPI - No user with id 327619532292096000 was found
13:00:15.601 [Timer-0] DEBUG d.b.j.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)
```

**Comment by Moudoux** [comment]
Hey, please compile the bot from sources yourself. The precompiled version is using an outdated version of the JavaCord library which does not support discord channel categories.

**Comment by kaxonomy** [comment]
Thanks that fixed it.
